export const CLICKED_ON_CLASS = "CLICKED_ON_CLASS";
export const ADD_CLASS = "ADD_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const CHANGE_STUDENT_INDEX = "CHANGE_STUDENT_INDEX";
export const CHANGE_TAKEN_ROLL = "CHANGE_TAKEN_ROLL";
