import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: "white",
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  baseText: {
    color: "orange",
    textAlign: "center",
    fontWeight: "bold",
    marginTop: 50,
    fontSize: 30,
    top: -40,
    textAlignVertical: "center",
  },
  box: {
    width: "32%",
    height: 100,
    backgroundColor: "orange",
    flexDirection: "row",
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 25,
    margin: 2,
    bottom: -50,
  },
  tinyDot: {
    width: 5,
    height: 5,
    backgroundColor: "#545454",
    borderRadius: 5 / 2,
    margin: 2,
    top: 15,
  },
  leftBox: {
    right: -5,
    top: 0,
    position: "absolute",
    alignItems: "center",
    alignContent: "center",
    width: 60,
    height: 60,
  },
  buttonText: {
    textAlign: "center",
    alignItems: "center",
    fontSize: 20,
    fontWeight: "bold",
    justifyContent: "center",
    margin: 12,
    textAlignVertical: "center",
    color: "#757575",
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 20,
    elevation: 20,
  },
  modalText: {
    fontSize: 20,
    textAlign: "center",
    color: "#363636",
  },
  box1: {
    flex: 0.25,
    backgroundColor: "white",
    borderRadius: 18,
    padding: 60,
    elevation: 2,
    top: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  photo: {
    height: 140 * 0.8,
    width: 140 * 0.8,
    borderRadius: (200 * 0.8) / 2,
    left: 35,
    bottom: 15,
    borderColor: "#d6d6d6",
    backgroundColor: "orange",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    flex: 1,
    justifyContent: "center",
  },
});
